# Generated by Django 4.1.7 on 2023-03-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='up_down',
            field=models.IntegerField(default=0),
        ),
    ]
