# Generated by Django 4.1.7 on 2023-03-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_votes_up_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='votes',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
