# Generated by Django 4.1.7 on 2023-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_votes_question_id_alter_votes_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
