# Generated by Django 4.1.7 on 2023-03-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_questions_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='vote',
        ),
    ]
