# Generated by Django 4.1.7 on 2023-03-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateField(null=True)),
                ('summary', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=50)),
                ('link', models.URLField(null=True)),
                ('writer', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
