# Generated by Django 4.1.7 on 2023-03-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0003_remove_book_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
    ]
