# Generated by Django 4.1.7 on 2023-03-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
