# Generated by Django 4.1.7 on 2023-03-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_country_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
