# Generated by Django 4.1.7 on 2023-03-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_country_alter_book_link_alter_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
